### ISSUE TITLE
--interval option does not work

### ISSUE THREAD

**Issue by avb1989** [zalando-stups/berry#18]
> $ sudo berry -m "bucket" -a "application_id" -i 200 . 
> WARNING: Could not load configuration from /etc/taupage.yaml: [Errno 2] No such file or directory: '/etc/taupage.yaml'
> INFO: Found credentials in shared credentials file: ~/.aws/credentials
> Traceback (most recent call last):
>   File "/usr/local/bin/berry", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.4/dist-packages/berry/cli.py", line 190, in main
>     run_berry(args)
>   File "/usr/local/lib/python3.4/dist-packages/berry/cli.py", line 170, in run_berry
>     time.sleep(args.interval)  # pragma: no cover
> TypeError: a float is required

System details : 
`$ python3 --version`
`Python 3.4.3`

`$ pip3 show stups-berry`
`---`
`Name: stups-berry`
`Version: 1.0.22`

**Comment by avb1989** [comment]
parser.add_argument('-i', '--interval', help='Interval in seconds', **type=int**, default=120)

Should be enough to make it work.

**Comment by hjacobs** [comment]
@avb1989 can you provide a PR? Thanks :smile:

**Comment by hjacobs** [comment]
This was fixed.
