### ISSUE TITLE
Berry is logging info to stderr

### ISSUE THREAD

**Issue by nhanloukiala** [zalando-stups/berry#20]
It seems that berry is putting INFO logs to `stderr`. It should not.

`[error] INFO: Found credentials in shared credentials file: ~/.aws/credentials`

**Comment by akauppi** [comment]
Could we have your team's comment on this?

The Picasso team (content broker) has an [issue](https://github.bus.zalan.do/Picasso/cb/issues/80) (internal link) depending on this. It's not major, and we could make a workaround, but the matter of using wrong `stdout`/`stderr` sounds simple enough that it should probably belong to you. This is not a feature request, but a bug.

Please inform of the plans on working on this - or just ignoring it.

**Comment by hjacobs** [comment]
Logging all error and informational output to `stderr` makes totally sense in the UNIX world. You don't want to clutter your pipe output with log lines.

Also look at `curl -v`, the log lines are all going to `stderr`:

```
curl -v http://google.com 2>/dev/null
```

So it makes only sense to have the Python logging output everything to `stderr` for consistency (even when `berry` does not have any expected `stdout`).

**Comment by akauppi** [comment]
Thanks, Henning, for the verdict. So we will treat this as a feature and not an error, and deal with it in the using application.

All I was worried, today, is why it takes so long to react to these issues. But we hadn't really pushed, either. All good. I'll check with @nhanloukiala but think this can be closed. Will mention your verdict in our dependent issue. Enjoy the weekend. :)
