### ISSUE TITLE
aws credentials are only fetched once

### ISSUE THREAD

**Issue by yuenking** [zalando-stups/berry#22]
This is a problem if we want to run something longer than an hour.

**Comment by hjacobs** [comment]
Can you provide more details? The description is very generic and not helpful at all.

**Comment by yuenking** [comment]
run_berry fetches the aws credentials once before the while loop; if the credentials are updated, berry will not know, and will continue trying to get the jsons using the expired credentials.

**Comment by hjacobs** [comment]
I see what you mean, I thought it would be about OAuth credentials from AWS :smirk:
