### ISSUE TITLE
Return error code when something goes wrong

### ISSUE THREAD

**Issue by dryewo** [zalando-stups/berry#5]
For example, I use `berry` like this in a script:

``` sh
berry -f berry.yaml --once creds/
```

And when there is a mistake (wrong `application_id`) in berry.yaml, it complains, but still returns 0, so that the script doesn't stop.

It would be useful to return 1 or other error-codes when an error occurs.

**Comment by hjacobs** [comment]
:+1: I agree, that's a bug

**Comment by akauppi** [comment]
Team Picasso in Helsinki is hurt by a similar case. Please fix / any estimate? (open since June - of LAST year)

I would use stronger words than @dryewo : returning non-zero for a command line tool is _required_, not just useful. STUPS tools should behave like any other command line tools.

**Comment by hjacobs** [comment]
@akauppi we are open for PRs :smirk:

**Comment by nhanloukiala** [comment]
@hjacobs berry is catching exception in every local function. 

If we want to fix this issue all together it means we have to modify in every function to escalate those exception to the main to return error code, and update all the unit test.

That is a lot of effort more than a minor bug fixing PR.

**Comment by akauppi** [comment]
@hjacobs We did consider contributing a PR as the first option. As @nhanloukiala describes above, we decided it was too evasive/elaborate.

This is an open source project. This is collaboration between Zalando employees on a baseline tool we are using. If you're planning not to do anything about this, would you please state so clearly. I understand you are busy but something elementary like discussing command line tool return values should not take up our time.

Link to the [issue](https://github.bus.zalan.do/Picasso/cb/issues/66) (internal) Picasso / Content broker is having on this.

Please suggest a course of action.
